from fpdf import FPDF
from datetime import datetime
from agent.schemas import DrugWatchResult, ClinicianData
import os


def _safe(text: str) -> str:
    """Strip characters outside Latin-1 so Helvetica doesn't throw."""
    return (
        str(text)
        .replace("—", " - ")   # em dash
        .replace("–", " - ")   # en dash
        .replace("’", "'")     # right single quote
        .replace("‘", "'")     # left single quote
        .replace("“", '"')     # left double quote
        .replace("”", '"')     # right double quote
        .replace("•", "*")     # bullet
        .replace("·", ".")     # middle dot
        .encode("latin-1", errors="replace")
        .decode("latin-1")
    )


class VigilPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(26, 22, 18)
        self.cell(0, 10, "VIGIL", ln=False)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 110, 95)
        self.cell(0, 10, "Pharmacovigilance Intelligence Brief", ln=True, align="R")
        self.set_draw_color(26, 22, 18)
        self.set_line_width(0.8)
        self.line(10, 20, 200, 20)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(160, 143, 126)
        self.cell(
            0, 10,
            _safe(f"Generated by Vigil - {datetime.now().strftime('%Y-%m-%d %H:%M')} - "
            "Not a substitute for clinical judgment"),
            align="C"
        )

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(26, 22, 18)
        self.set_fill_color(245, 241, 234)
        self.cell(0, 7, _safe(title.upper()), ln=True, fill=True)
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(60, 50, 40)
        self.multi_cell(0, 5, _safe(text))
        self.ln(1)

    def label_value(self, label: str, value: str):
        label_w = 45
        value_w = self.w - self.l_margin - self.r_margin - label_w
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(90, 80, 68)
        self.cell(label_w, 5, _safe(label + ":"), ln=False)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(26, 22, 18)
        self.multi_cell(value_w, 5, _safe(value))


SEVERITY_LABEL = {
    "critical": "[CRITICAL]",
    "moderate": "[MODERATE]",
    "informational": "[INFO]",
}

DDI_SEVERITY_LABEL = {
    "contraindicated": "[CONTRAINDICATED]",
    "major": "[MAJOR]",
    "moderate": "[MODERATE]",
    "minor": "[MINOR]",
}


def generate_brief(
    result: DrugWatchResult,
    clinician_data: ClinicianData,
    velocity_data: dict,
    scorecard: list,
    comparison: dict = None,
    output_path: str = "/tmp/vigil_brief.pdf",
) -> str:
    """
    Generate a clinical brief PDF.
    Returns path to the generated file.
    """
    pdf = VigilPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Cover info ────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(26, 22, 18)
    pdf.cell(0, 10, _safe(result.drug_name.title()), ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 110, 95)
    pdf.cell(0, 5, _safe(f"Clinical Safety Brief - {datetime.now().strftime('%B %d, %Y')}"), ln=True)
    pdf.cell(
        0, 5,
        _safe(f"Sources: {', '.join(result.sources_queried)} - "
        f"{result.total_documents_scanned} documents scanned - "
        f"{result.query_duration_seconds}s"),
        ln=True
    )
    pdf.ln(6)

    # ── Safety signals ────────────────────────────────────────────
    pdf.section_title("Safety Signals")
    severity_order = {"critical": 0, "moderate": 1, "informational": 2}
    sorted_signals = sorted(result.signals, key=lambda s: severity_order.get(s.severity, 3))

    for sig in sorted_signals:
        label = SEVERITY_LABEL.get(sig.severity, "")
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(
            180 if sig.severity == "critical" else
            140 if sig.severity == "moderate" else 40,
            40 if sig.severity == "critical" else
            90 if sig.severity == "moderate" else 100,
            40,
        )
        pdf.cell(0, 5, _safe(f"{label} {sig.signal_type.replace('_', ' ').title()} - {sig.source_name}"), ln=True)
        pdf.label_value("Population", sig.population_affected)
        pdf.label_value("Summary", sig.summary)
        pdf.label_value("Action", sig.recommended_action)
        if sig.date_detected:
            pdf.label_value("Date", sig.date_detected)
        pdf.ln(2)

    # ── Velocity ──────────────────────────────────────────────────
    if velocity_data.get("any_rising"):
        pdf.section_title("Rising Signal Alert")
        rising = ", ".join(velocity_data.get("rising_sources", [])).upper()
        pdf.body_text(
            f"Publication volume for {result.drug_name} is accelerating in: {rising}. "
            "This may indicate an emerging safety concern requiring active monitoring."
        )

    # ── Safety scorecard ──────────────────────────────────────────
    if scorecard:
        pdf.section_title("Therapeutic Alternatives — Safety Comparison")
        for entry in scorecard:
            marker = " <- (searched)" if entry.get("is_target") else ""
            pdf.label_value(
                entry["drug"].title() + marker,
                f"Safety score: {entry['safety_score']}/100  |  "
                f"Critical: {entry['critical']}  Moderate: {entry['moderate']}  Info: {entry['informational']}"
            )

    # ── Drug-drug interactions ────────────────────────────────────
    if clinician_data.interactions:
        pdf.section_title("Drug-Drug Interactions")
        for ix in clinician_data.interactions:
            label = DDI_SEVERITY_LABEL.get(ix.severity, "")
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(26, 22, 18)
            pdf.cell(0, 5, _safe(f"{label} {ix.drug_a.title()} + {ix.drug_b.title()}"), ln=True)
            pdf.label_value("Mechanism", ix.mechanism)
            pdf.label_value("Effect", ix.clinical_effect)
            pdf.label_value("Management", ix.management)
            pdf.label_value("Evidence", ix.evidence_level.title())
            pdf.ln(2)

    # ── Dosing ────────────────────────────────────────────────────
    if clinician_data.dosing:
        pdf.section_title("Therapeutic Dosing")
        for d in clinician_data.dosing:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(26, 22, 18)
            pdf.cell(0, 5, _safe(d.indication), ln=True)
            pdf.label_value("Standard dose", f"{d.standard_dose} {d.route} {d.frequency}")
            if d.renal_adjustment:
                pdf.label_value("Renal adjustment", d.renal_adjustment)
            if d.hepatic_adjustment:
                pdf.label_value("Hepatic adjustment", d.hepatic_adjustment)
            if d.paediatric_dose:
                pdf.label_value("Paediatric", d.paediatric_dose)
            if d.max_dose:
                pdf.label_value("Max dose", d.max_dose)
            pdf.ln(2)

    # ── Special populations ───────────────────────────────────────
    sp = clinician_data.special_populations
    if sp:
        pdf.section_title("Special Populations")
        pdf.label_value("Pregnancy", f"{sp.pregnancy_category} - {sp.pregnancy_notes}")
        pdf.label_value("Lactation", f"{sp.lactation_safety.title()} - {sp.lactation_notes}")
        pdf.label_value("Geriatric", sp.geriatric_precautions)
        pdf.label_value("Paediatric", sp.paediatric_restriction)

    # ── Pharmacogenomics ──────────────────────────────────────────
    if clinician_data.pharmacogenomics:
        pdf.section_title("Pharmacogenomics")
        for pgx in clinician_data.pharmacogenomics:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(26, 22, 18)
            pdf.cell(0, 5, _safe(f"{pgx.gene} - {pgx.variant}"), ln=True)
            pdf.label_value("Clinical impact", pgx.clinical_impact)
            pdf.label_value("Recommendation", pgx.recommendation)
            pdf.label_value("Evidence", pgx.evidence_level.title())
            pdf.ln(2)

    # ── Africa formulary ──────────────────────────────────────────
    af = clinician_data.africa_formulary
    if af:
        pdf.section_title("Africa Formulary Status")
        pdf.label_value("NAFDAC (Nigeria)", af.nafdac_status)
        pdf.label_value("SAHPRA (South Africa)", af.sahpra_status)
        pdf.label_value("WHO Prequalified", "Yes" if af.who_prequalified else "No")
        pdf.label_value("Availability notes", af.availability_notes)

    # ── Head-to-head comparison ───────────────────────────────────
    if comparison:
        drug_a = comparison.get("drug_a", "Drug A").title()
        drug_b = comparison.get("drug_b", "Drug B").title()
        pdf.section_title(f"Head-to-Head Comparison: {drug_a} vs {drug_b}")
        eff = comparison.get("efficacy", {})
        if eff.get("superiority_notes"):
            pdf.label_value("Superiority", eff.get("superiority_notes", ""))
        if eff.get("head_to_head_summary"):
            pdf.label_value("Direct RCT", eff["head_to_head_summary"])
        gl = comparison.get("guidelines", {})
        if gl.get("preferred_drug"):
            pdf.label_value("Guideline preference", gl["preferred_drug"].title())
        if gl.get("preferred_rationale"):
            pdf.label_value("Rationale", gl["preferred_rationale"])
        if gl.get("africa_context"):
            pdf.label_value("Africa context", gl["africa_context"])

    pdf.output(output_path)
    return output_path
